const { contextBridge, ipcRenderer } = require("electron");

const invoke = (channel, payload) => ipcRenderer.invoke(channel, payload);

contextBridge.exposeInMainWorld("ownerLedger", {
  isReady: () => invoke("app:isReady"),
  completeSetup: (payload) => invoke("setup:complete", payload),
  getDashboard: (targetMonth) => invoke("dashboard:get", targetMonth),
  listProperties: () => invoke("properties:list"),
  createProperty: (input) => invoke("properties:create", input),
  archiveProperty: (id) => invoke("properties:archive", id),
  listUnits: () => invoke("units:list"),
  createUnit: (input) => invoke("units:create", input),
  listTenants: () => invoke("tenants:list"),
  createTenant: (input) => invoke("tenants:create", input),
  listContracts: () => invoke("contracts:list"),
  createContract: (input) => invoke("contracts:create", input),
  generateMonthlyCharges: (targetMonth) => invoke("charges:generateMonthly", targetMonth),
  listMonthlyCharges: (targetMonth) => invoke("charges:list", targetMonth),
  listSpotCharges: () => invoke("spotCharges:list"),
  createSpotCharge: (input) => invoke("spotCharges:create", input),
  listPayments: () => invoke("payments:list"),
  createPayment: (input) => invoke("payments:create", input),
  findAllocationCandidates: (paymentId) => invoke("allocations:candidates", paymentId),
  createAllocation: (input) => invoke("allocations:create", input),
  cancelAllocation: (id) => invoke("allocations:cancel", id),
  importPaymentCsv: (rows, fileName) => invoke("payments:importCsv", { rows, fileName }),
  listAllocations: (paymentId) => invoke("allocations:list", paymentId),
  listExpenses: () => invoke("expenses:list"),
  createExpense: (input) => invoke("expenses:create", input),
  cancelExpense: (id) => invoke("expenses:cancel", id),
  listDepositTransactions: () => invoke("deposits:list"),
  createDepositTransaction: (input) => invoke("deposits:create", input),
  cancelDepositTransaction: (id) => invoke("deposits:cancel", id),
  listRepairs: () => invoke("repairs:list"),
  createRepair: (input) => invoke("repairs:create", input),
  linkRepairExpense: (input) => invoke("repairs:linkExpense", input),
  listDocuments: () => invoke("documents:list"),
  attachDocument: (input) => invoke("documents:attach", input),
  archiveDocument: (id) => invoke("documents:archive", id),
  getReportSummary: (targetYear) => invoke("reports:summary", targetYear),
  exportTaxCsv: (targetYear) => invoke("reports:exportTaxCsv", targetYear),
  createBackup: (directory) => invoke("backup:create", directory),
  restoreBackup: () => invoke("backup:restore")
});
